### ISSUE TITLE
PackTracker crashed

### ISSUE THREAD

**Issue by lilmentor** [MGK82/PackTracker#16]
Hi,

First off, thank you for making such an awesome plugin.

So my issue is that with the first WitchWood pack I opened, the plugin crashed and didn't record my first pack. Now, I wouldn't care so much but un(fortunately) the first pack contained a legendary.

I tried to manually edit the xml file but I don't have the codes for the cards. Anyway you can tell me how I can manually enter this info

Time 4/12 pack time="636591363875823560" (this is the time of the 2nd pack so any time before that should work)
Bewitched Guardian
Vilebrood Skitterer
Shudderwock (free)
Fiendish Circle
Glinda Crowskin
Lost Spirit

**Comment by mgk-11com7** [comment]
Hi there, sorry that Pack Tracker didn't work as intended. When it crashes, can you give some more information if possible? It works fine here. Was there something like an error/exception message, stack trace or anything showing up? That would realy help to identify the problem and fix it.

Because I am at the office right now and not at home, I would like to forward you to an older ticket, where I already explained how to add entries manually to the history, rather than figuring out the data in my work time. You don't need to care about the order of entries.
https://github.com/MGK82/PackTracker/issues/5

**Comment by lilmentor** [comment]
No need to be sorry! Again, thank you for making this plugin. It is one of my favorites. Sorry I didn't make myself clear, but it crashed before I updated the plugin. I updated it and it now works perfectly. I was just more wondering how to manually enter that one pack that wasn't counted. The information you gave me is exactly what I was looking for!
