### ISSUE TITLE
Incorrect pity timer values & other issues

### ISSUE THREAD

**Issue by please55** [MGK82/PackTracker#7]
So far opened 4 regular KFT packs and in the bar graph it says 4/9 for epics.  I don't understand what that means.  Isn't the pity timer for epics 10 packs and similarly for legendaries its 40 and not 39?

The bar graph start on 2 on the x-axis.  Why?  What does the 2 represent?  You've added horizontal orange and red lines to the graph as well.  Why is it significant that you have an orange line at y value 4 and 9 for epics bar graph?  Its confusing.  If it does mean something, the meaning isn't clear or communicated well.

**Comment by MGK82** [comment]
It's x/9 and x/39 because the 10th and 40th pack *must* contain an epic/leg, which will reset the counter to 0. You cannot have a 10 or 40 there unless you messed up the data.

The graph starts on 2, because it _waits_ for the first epic/leg to reset the pity timer. It's the only way to align with it. Taking it into account would falsify the data. Therefor the 1th doesn't go into the chart. All windows update on the fly when you open a pack, but the lib for the charts that HDT uses doesn't seem to give a proper way to do that for the labels. I would need to re-render the graphs when I want to change the labels. I'll stick to that lib to keep PackTracker small and don't have to contribute a different lib with it. But I'll try to find a work around later, atm it does not have priority because it's a minor problem. Long story short: Before you have opened your first epic/leg, the "2" doesn't mean anything and after that, its your seconds pack with an epic/leg, followed by the 3rd (which goes into a new bar) and so on.

The orange line is on 4 because 5 is the avarege that blizzard wants. Once you passes orange, you are above the general average. There is also a red line on 9/39, which you should never be able to pass and a dotted green line which is your personal average (this one comes in with more data).

It's a screenshot of my kft with more data. I hope it can clear things up a bit. The 1st is skipped, then regular recordings and the half transperent (right) bar is the current counting pity timer. I had 24 packs with epics and are currently working on my 25th where i am 6 into. Max 3 more packs *without* an epic.
![image](https://user-images.githubusercontent.com/12571300/31318827-9e63c72a-ac58-11e7-92d0-190850963ef7.png)

And I actually should make some kind of info-thingy. That's right. For me, it makes perfect sense because it comes out of my brain. ^^ You know? I'll see if I put something into the next update. Stay tuned and have your auto-update enabled, that you can find in the plugin's settings (options -> plugins -> select "packtracker" -> settings). If anything remained unclear or if you have any suggestions, just contact me again. You can also send me an email to the adress that you can find in the settings under credits.

**Comment by please55** [comment]
Thank  you very much for your explanation!  Someone asked similar question on reddit so I will copy it there.

**Comment by MGK82** [comment]
I already replied there.

**Comment by MGK82** [comment]
FYI: I found a way to replace the labels on the fly and we did some testing, my friends and I, to see how it works the best. From starting at 1 and switching to 2 later or having the current one labeled with "current" etc. we ended up with removing the labels completely. The value of information is not that high and it only confuses people. They found the main reason is to see how your current pity timer is and all the rest is secondary or distracting. Along with that we decided to make some other minor appearance changes for both, the pity timer window and the pity timer overlay. It all comes in the next release.
